application:
 name: litigation
server:
 port: 9090
spring:
 datasource:
    url: jdbc:mariadb://localhost:3306/litigation
    username: root
    password: 5418feliX
 driverClassName: org.mariadb.jdbc.Driver
 jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
 servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
 rabbitmq:
    host: 172.24.0.1
    port: 5672
    username: felix
    password: 56725672
    virtual-host: /
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
