spring:
 application:
    name: litigation
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/litigationb?useSSL=false&serverTimezone=UTC
    username: root
    password: 5418feliX
 cloud:
    config:
      uri: http://localhost:8888
 jpa:
    properties:
      hibernate:
        validator:
          message_interpolator: org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
server:
 port: 9090
eureka:
 client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/
    register-with-eureka: true
    fetch-registry: true
rabbitmq:
 host: localhost
 port: 5672
 username: felix
 password: 56725672
