spring:
 application:
    name: litigation
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/litigationb?useSSL=false&serverTimezone=UTC
    username: root
    password: 5418feliX
 jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
 servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
 rabbitmq:
    host: 172.24.0.1
    port: 5672
    username: felix
    password: 56725672
eureka:
 client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/
spring:
 config:
    import: configserver:
server:
 port: 9090
